import React from 'react'
import { notFound } from 'next/navigation'

import './index.scss'

const baseClass = 'multi-tenant'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'Next.js',
}

// eslint-disable-next-line no-restricted-exports
export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Headless by default: only expose frontend routes when explicitly enabled.
  if (process.env.PAYLOAD_ENABLE_FRONTEND !== 'true') {
    notFound()
  }

  return (
    <html className={baseClass} lang="en">
      <body>{children}</body>
    </html>
  )
}
